colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true

mainSections = ["posts"]
fingerprintAlgorithm = "sha256"

dateFormat = "2 January 2006"
description = "The blog of an engineer from Canada"
subtitle = "The blog of an engineer from Canada"
keywords = ["coding", "electronics", "3d printing", "sysadmin", "kubernetes"]

[author]
name = "Will Warren"
image = "me.jpeg"
headline = "Coding, 3D Printing, Electronics"
bio = "Coding, 3D Printing, Electronics"
links = [
  { github = "https://github.com/phybros" },
  { bluesky = "https://bsky.app/profile/willdavidwarren.bsky.social" },
  { mastodon = "https://hachyderm.io/@willwarren" },
]

[header]
layout = "hybrid"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
recentLimit = 10

[article]
showDate = true
showDateUpdated = false
showAuthor = false
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = false
showComments = true
sharingLinks = ["facebook", "mastodon", "bluesky", "reddit", "linkedin"]

[kommentar]
apiUrl = "https://trj7mjckc3.execute-api.us-east-1.amazonaws.com/prod/comments"
bucketUrl = "https://kommentar-publicbucket-k2hm5mdwgywm.s3.us-east-1.amazonaws.com/comments"
cognitoDomain = "kommentar-87e1cd40-261f-11f1-9515-122419eb6ddf.auth.us-east-1.amazoncognito.com"
cognitoClientId = "5bdor8gg9prm0uad2mohrhs87n"
formMessage = "All comments will be moderated"

[list]
showBreadcrumbs = true
showSummary = false
showTableOfContents = false
showTaxonomies = true
groupByYear = true
paginationWidth = 1

[taxonomy]
showTermCount = true
